<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-</name>
   <tag></tag>
   <elementGuidId>180aa42a-947d-4841-9704-dcec4476f13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='um_field_667_father_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#um_field_667_father_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>841974a8-7982-4d6e-ab51-fdfb1b77277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>um_field_667_father_name</value>
      <webElementGuid>b28b1d1c-ca74-427b-85f6-01e2517f069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-field um-field-text  um-is-conditional um-field-father_name um-field-text um-field-type_text</value>
      <webElementGuid>050660e0-1b9c-4f64-b964-7aa1c2c008b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>father_name</value>
      <webElementGuid>5bb0da05-cd3e-42f1-9aad-18bd1bca07fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cond-0-action</name>
      <type>Main</type>
      <value>show</value>
      <webElementGuid>fbf19cb7-a123-4d03-9c3d-4c2e7a840adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cond-0-field</name>
      <type>Main</type>
      <value>patient_information</value>
      <webElementGuid>e3d39c77-d36f-4ffc-beaa-0eb493f43582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cond-0-operator</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>2f41a9bd-73e8-44b7-a900-049fe4c7a9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ชื่อ-นามสกุล บิดา*

						</value>
      <webElementGuid>ac51a129-0a54-4a11-87be-a91aaa010719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um_field_667_father_name&quot;)</value>
      <webElementGuid>04338d55-4703-4723-b24b-c9f78bbf611a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_father_name']</value>
      <webElementGuid>857e5b3f-1946-4d83-8c52-dba852e7e2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-673']/div/div/div[3]/div[2]/div/div/div/div/div[2]/div/div/div[3]/div/div/form/div[3]/div/div[3]</value>
      <webElementGuid>4f219cf5-db5a-4857-be40-1b2a6e5d59c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='บุคคลในครอบครัว'])[1]/following::div[1]</value>
      <webElementGuid>0f6d252b-3d54-4447-94ee-e3392ddbd6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='หมู่เลือด*'])[1]/following::div[9]</value>
      <webElementGuid>d1c2bd65-b6ae-4330-9c82-57a9df98f5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชื่อ-นามสกุล มารดา*'])[1]/preceding::div[4]</value>
      <webElementGuid>08e1791c-a463-49de-9515-c7e9e9d970e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]</value>
      <webElementGuid>5dfff070-cc47-4740-86c2-831a426f4e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'um_field_667_father_name' and (text() = 'ชื่อ-นามสกุล บิดา*

						' or . = 'ชื่อ-นามสกุล บิดา*

						')]</value>
      <webElementGuid>5bc918c1-7db2-4775-b15b-4ce735a1594d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
