<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__um-icon-android-radio-button-off</name>
   <tag></tag>
   <elementGuidId>07db819c-777f-47c3-ba1b-44009849e4d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='um_field_667_drug_allergy_history']/div[2]/label[3]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cfb6550f-a995-463e-a39c-762e0dc8a31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-icon-android-radio-button-off</value>
      <webElementGuid>1c39c5da-d4ae-45b7-8b18-8df457e8d54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um_field_667_drug_allergy_history&quot;)/div[@class=&quot;um-field-area&quot;]/label[@class=&quot;um-field-radio  um-field-half&quot;]/span[@class=&quot;um-field-radio-state&quot;]/i[@class=&quot;um-icon-android-radio-button-off&quot;]</value>
      <webElementGuid>265b66fa-2d66-4d45-97c9-01fbbe7f6719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_drug_allergy_history']/div[2]/label[3]/span/i</value>
      <webElementGuid>101e3234-997e-41b4-a564-5791dd71c271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/span/i</value>
      <webElementGuid>e893bb3f-6bc9-41f9-9419-c6475d763fd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
