<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Email_um-icon-android-checkbox-outline-blank</name>
   <tag></tag>
   <elementGuidId>cf37a5bc-4859-461a-804c-31c85c8c7d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='um_field_667_accept_data']/div/label/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.um-field-checkbox.um-field-half.um-field-radio-state-disabled > span.um-field-checkbox-state > i.um-icon-android-checkbox-outline-blank</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>abd78e8a-c32b-4d13-bba5-7b4509a0c800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-icon-android-checkbox-outline-blank</value>
      <webElementGuid>42c7cd04-994c-4ced-a7ce-2b7f1fb0ba61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um_field_667_accept_data&quot;)/div[@class=&quot;um-field-area&quot;]/label[@class=&quot;um-field-checkbox  um-field-half  um-field-radio-state-disabled&quot;]/span[@class=&quot;um-field-checkbox-state&quot;]/i[@class=&quot;um-icon-android-checkbox-outline-blank&quot;]</value>
      <webElementGuid>c80629fc-b5b8-4104-ade2-9541026506c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_accept_data']/div/label/span/i</value>
      <webElementGuid>2acc5d09-1fff-4c87-bf39-2de70f841610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/div/label/span/i</value>
      <webElementGuid>4fabf63f-1ea4-482f-8005-2807c4ebf71c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
