<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Only fill in if you are not human_a-_bb7876</name>
   <tag></tag>
   <elementGuidId>a411895f-b3f9-4db3-98d3-dfb4190ea2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-awedoh7m4cs8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-awedoh7m4cs8&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b2438fbd-f013-4c3a-8302-333aa33f17df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>b0d19eb0-ca25-4a37-a995-68563398a506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeUuuUUAAAAAFUUFsjnzBm8Q-eSVYS0iu38Zesg&amp;co=aHR0cHM6Ly93d3cuZ2oubWFoaWRvbC5hYy50aDo0NDM.&amp;hl=th&amp;type=image&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;theme=light&amp;size=normal&amp;cb=9612wca1cj0p</value>
      <webElementGuid>c1a8e1d0-184f-464e-b7ea-41aa28d9245e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>3e74bdec-75d5-4558-aede-0e8df05b715f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e7745c3a-d804-4dad-9231-b1e70a4241cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>12e644ab-4f2e-47aa-a718-2c81b2d3c540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-awedoh7m4cs8</value>
      <webElementGuid>949c6089-3ca4-4140-a046-76626558978c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8177d475-6412-45fa-a516-08ff37690de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f2e6fdf1-e150-4942-81bc-5dbc07eac4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>4e31dff9-fe71-4167-85cb-7ad98ea67994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um-667&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>fff18d1a-b405-42a0-a67f-622586769d96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-awedoh7m4cs8']</value>
      <webElementGuid>34e68743-ed5c-4605-8f5f-4eba9b884355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um-667']/div/div/iframe</value>
      <webElementGuid>c456f354-2c1e-41cc-9e67-f00e00a8e33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f8f1376f-fa7a-44a9-8e6d-f541c00214e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeUuuUUAAAAAFUUFsjnzBm8Q-eSVYS0iu38Zesg&amp;co=aHR0cHM6Ly93d3cuZ2oubWFoaWRvbC5hYy50aDo0NDM.&amp;hl=th&amp;type=image&amp;v=6MY32oPwFCn9SUKWt8czDsDw&amp;theme=light&amp;size=normal&amp;cb=9612wca1cj0p' and @name = 'a-awedoh7m4cs8']</value>
      <webElementGuid>f8c25865-74f9-4ef8-a86e-5dbf99810db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
