<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__related_as-667</name>
   <tag></tag>
   <elementGuidId>548cc4e0-8718-4121-8ed1-2ff17f7e0bf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='related_as-667']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#related_as-667</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c3d4cfa-14aa-484f-98f6-e04012d7efed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c5aa2e7d-67cc-4ee2-b662-b6922c616090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid not-required </value>
      <webElementGuid>faec950d-c777-492c-bac8-f3316d5d0cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b09d8c9-62f6-4217-a105-98fdf23b1669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>related_as-667</value>
      <webElementGuid>f38fbb9a-5c7d-40f8-ac04-d25be3efc2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>related_as-667</value>
      <webElementGuid>e7de9b65-44ff-47dc-b12c-894df3b8563b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>เพื่อน, พี่, น้า, ป้า</value>
      <webElementGuid>1e83bc09-c7b5-48ce-a4f0-11b9c1a2facc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>related_as</value>
      <webElementGuid>243cecf5-8f59-4f7b-ae68-b6e0472d8be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;related_as-667&quot;)</value>
      <webElementGuid>82dc0ac7-a8fb-424c-b360-a56dee8f2e09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='related_as-667']</value>
      <webElementGuid>3e56577d-fed7-4a9f-89f2-2dc200e0ef4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_related_as']/div[2]/input</value>
      <webElementGuid>c1c7da05-4121-40cc-b461-aa8e8853e44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/input</value>
      <webElementGuid>735a909c-7b47-44d6-8cac-aa6e3c234d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'related_as-667' and @id = 'related_as-667' and @placeholder = 'เพื่อน, พี่, น้า, ป้า']</value>
      <webElementGuid>374177ea-0379-4051-9aa1-bd4a15a9e902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
