<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phone_home-667</name>
   <tag></tag>
   <elementGuidId>2873fc3b-4747-400d-ab07-fd18710ced7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone_home-667']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phone_home-667</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ddd9266-1e89-49ad-b5c5-cc78beeaed4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e12c44df-7d0c-4835-bf49-3ba8e6719ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid not-required </value>
      <webElementGuid>a0a811b4-66fd-433b-88a8-c3f7c74c5216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5bd18af-bd81-4dc5-bb32-a39a5cc386fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_home-667</value>
      <webElementGuid>8cd6b438-c74c-47bb-877d-2fe73ffb7315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone_home-667</value>
      <webElementGuid>3dada23d-74e9-4f23-ae59-511d17be6c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>phone_number</value>
      <webElementGuid>e7c05c24-957e-413c-ae42-25981e7bd674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>phone_home</value>
      <webElementGuid>70a9e33b-0af5-4478-8199-b8690b47603c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone_home-667&quot;)</value>
      <webElementGuid>c196213b-a99a-418c-a14d-f071f71684e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone_home-667']</value>
      <webElementGuid>af29a1f1-d450-4123-84eb-81135921f7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_phone_home']/div[2]/input</value>
      <webElementGuid>794be5bd-b20b-4f98-8385-9d1f9bbf8492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/input</value>
      <webElementGuid>9228366f-57fc-4a56-9186-efd4a57fec23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'phone_home-667' and @id = 'phone_home-667']</value>
      <webElementGuid>323701f0-ddaa-49d5-b3e0-1850b837459b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
