<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__house_number-667</name>
   <tag></tag>
   <elementGuidId>e1904ea0-3104-4b8c-9549-5dc0c49dccf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='house_number-667']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#house_number-667</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07f8ca10-728c-408f-9b7b-b1badee67f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>462463c3-4ad3-4ee8-aa10-3fa9587330bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid not-required </value>
      <webElementGuid>9ef53f32-a954-444f-85fc-6342c45f2550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94917437-527d-4ae3-bb55-93452b91a91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>house_number-667</value>
      <webElementGuid>502ea2c2-e7c0-4e8c-82eb-1a5f9bfba09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>house_number-667</value>
      <webElementGuid>245c1daa-bea2-4360-9a9f-a156d7f18cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>house_number</value>
      <webElementGuid>d4419a21-7d81-4306-b144-a81655ad59c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;house_number-667&quot;)</value>
      <webElementGuid>180eb914-fe4b-475e-91f0-63d850b1e758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='house_number-667']</value>
      <webElementGuid>9f48960f-0280-4399-adce-2ad9104bc80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_house_number']/div[2]/input</value>
      <webElementGuid>b4a03be9-e352-4691-b512-ce2520a5304f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/input</value>
      <webElementGuid>c51df1b8-3536-4257-8ad1-6f767dbe2fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'house_number-667' and @id = 'house_number-667']</value>
      <webElementGuid>6ec7e5ea-34f6-454f-b3d2-f7baf517d20c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
