<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user_password-667</name>
   <tag></tag>
   <elementGuidId>7c2643c9-b3e7-403c-bee7-174d0da0624a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_password-667']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_password-667</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6767d8b-a6f4-4e5a-8b3f-c5049f26bcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid </value>
      <webElementGuid>35f18877-663e-45a2-8e94-1aeecbfb3015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>adbf371f-78c7-4626-af4d-d279647d1dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_password-667</value>
      <webElementGuid>05103674-5363-4bc2-852a-74166eedc66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_password-667</value>
      <webElementGuid>1c142d93-742c-49dc-b1be-a662177cd1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*รหัสผ่านต้องมีความยาวมากกว่า 8 ตัว และต้องมีอักษรพิมพ์เล็ก พิมพ์ใหญ่</value>
      <webElementGuid>d3c36abe-b1f3-46da-b574-b1de99483a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>user_password</value>
      <webElementGuid>83661fe2-f803-4467-8904-429726f8f76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_password-667&quot;)</value>
      <webElementGuid>245e276b-e12b-4cad-a74f-36fd7f83c4cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_password-667']</value>
      <webElementGuid>893a351a-df2a-467c-bba7-0eef06d9aaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_user_password']/div[2]/input</value>
      <webElementGuid>d7f4a032-8125-4478-9489-5eb32eb8e177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>c5f850a8-a2c1-4b21-93a4-4dcbc9dfcc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'user_password-667' and @id = 'user_password-667' and @placeholder = '*รหัสผ่านต้องมีความยาวมากกว่า 8 ตัว และต้องมีอักษรพิมพ์เล็ก พิมพ์ใหญ่']</value>
      <webElementGuid>d4c310c3-8e9c-4f5d-a10e-f8fbbbbd148e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
