<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm_confirm_user_password-667</name>
   <tag></tag>
   <elementGuidId>e071295b-f7a9-41bc-8b0d-a17be9a42c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_user_password-667']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirm_user_password-667</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50848a7e-e067-41aa-ad36-545b18053682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid um-validate-not-matched</value>
      <webElementGuid>29e0e169-a2ee-4d67-98f2-24bcd3c3da0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ad1734c4-c61e-4e65-87bb-87b7829d038f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_user_password-667</value>
      <webElementGuid>f8e38127-e00c-470b-a7e4-dee161a3f613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_user_password-667</value>
      <webElementGuid>80775138-1293-4f0d-8e78-de0f2f34db7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*รหัสผ่านต้องมีความยาวมากกว่า 8 ตัว และต้องมีอักษรพิมพ์เล็ก พิมพ์ใหญ่</value>
      <webElementGuid>2f8faf8c-2b75-4d25-94b3-65b06eaa8a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>confirm_user_password</value>
      <webElementGuid>d6152739-776c-4752-a59c-e0a9c5f37987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_user_password-667&quot;)</value>
      <webElementGuid>3482a7e9-f910-4791-9cdf-f5c2ae02e5e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_user_password-667']</value>
      <webElementGuid>991ca64a-acaa-4ffd-9f0f-836265f9730c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_confirm_user_password']/div[2]/input</value>
      <webElementGuid>f9f57353-d858-478e-b2e8-01c79b042bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/input</value>
      <webElementGuid>4535a099-ee3e-4b39-bc53-267d01c4ca89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_user_password-667' and @id = 'confirm_user_password-667' and @placeholder = '*รหัสผ่านต้องมีความยาวมากกว่า 8 ตัว และต้องมีอักษรพิมพ์เล็ก พิมพ์ใหญ่']</value>
      <webElementGuid>a2f9bb6e-cbed-4691-9e6c-020e02a0fadc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
