<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__select2-gender_d-container</name>
   <tag></tag>
   <elementGuidId>e8ed866a-ce91-4244-ac97-5005a464bcaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-gender_d-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-gender_d-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a451bf68-84a8-4204-87cd-ebd14b5af82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9adfe20d-1116-4661-8dbf-ab10070cd1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-gender_d-container</value>
      <webElementGuid>76252089-8761-4cbb-a2c3-a155e12b995b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7622f7c3-6df4-4877-b6ad-b978f3f1f651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>666a684b-5421-4fe0-b26d-22597d62ce57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-gender_d-container&quot;)</value>
      <webElementGuid>7af8d057-8625-47d5-904a-69ca18ed3a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-gender_d-container']</value>
      <webElementGuid>57197141-fe9d-49b4-9ec1-4cb481719fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_667_gender_d']/div[2]/span/span/span/span</value>
      <webElementGuid>d0f1345b-4871-4660-90c2-0eb4794a138f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เพศ*'])[1]/following::span[4]</value>
      <webElementGuid>f93d78ce-cfdc-4e8e-8d2f-9953ca51ea76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เลขบัตรประชาชน*'])[1]/following::span[4]</value>
      <webElementGuid>617ab85c-b7ec-4410-9f4e-f05bc2d8d937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สถานภาพสมรส*'])[1]/preceding::span[4]</value>
      <webElementGuid>e0c56b69-a01d-4b4f-baa4-683c025233f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เกิดวันที่*'])[1]/preceding::span[11]</value>
      <webElementGuid>570b552f-fe5e-426f-93c2-eb7719b03316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[2]/span/span/span/span</value>
      <webElementGuid>af5af7f2-9f6f-42f8-abad-f1221779b016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-gender_d-container']</value>
      <webElementGuid>5203aaca-7fb0-4407-9aa3-0ab19f59b980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
